version: '3.8'

services:
  # База для todo-service
  postgres-todo:
    image: postgres:15
    container_name: postgres-todo
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1314
    ports:
      - "5432:5432"
    volumes:
      - postgres-todo-data:/var/lib/postgresql/data

  # База для reminder-service
  postgres-reminder:
    image: postgres:15
    container_name: postgres-reminder
    environment:
      POSTGRES_DB: reminder_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1314
    ports:
      - "5433:5432"
    volumes:
      - postgres-reminder-data:/var/lib/postgresql/data

  # Todo Service
  todo-service:
    build:
      context: ./todo-service
    container_name: todo-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres-todo
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-todo:5432/todo_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1314

  # Reminder Service
  reminder-service:
    build:
      context: ./reminder-service
    container_name: reminder-service
    ports:
      - "8081:8080"
    depends_on:
      - postgres-reminder
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-reminder:5432/reminder_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1314

volumes:
  postgres-todo-data:
  postgres-reminder-data:
