version: '3.8'

services:
  postgres-todo:
    image: postgres:15
    container_name: postgres-todo
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1314
    ports:
      - "5434:5432"
    volumes:
      - todo_data:/var/lib/postgresql/data

  postgres-reminder:
    image: postgres:15
    container_name: postgres-reminder
    environment:
      POSTGRES_DB: reminder_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1314
    ports:
      - "5433:5432"
    volumes:
      - reminder_data:/var/lib/postgresql/data

  todo-service:
    build:
      context: ./todo-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-todo:5432/todo_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1314
    depends_on:
      - postgres-todo

  reminder-service:
    build:
      context: ./reminder-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-reminder:5432/reminder_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1314
    depends_on:
      - postgres-reminder

volumes:
  todo_data:
  reminder_data: